version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: vue_ssr_image
    container_name: web
    command: nodemon server
    ports:
      - '80:8080'
    restart: always
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules